### ISSUE TITLE
Problem building a  parity web-app (picking up incorrect github version)

### ISSUE THREAD

**Issue by johnwhitton** [tomusdrw/parity-webapp#1]
Hi,

I'm trying to build my first parity web application and have been following the instructions on the readme.md
I've created a new repository [parity-polyapp](https://github.com/johnwhitton/parity-polyapp) and also have forked the [parity repo to my own local repository](https://github.com/johnwhitton/parity) 

The problem I'm having is that when I first edited my [cargo.toml in parity-polydapp](https://github.com/johnwhitton/parity-polyapp/blob/master/Cargo.toml) I didn't add the [parity-webapp dependancy](https://github.com/johnwhitton/parity-polyapp/blob/master/Cargo.toml#L9).
I've since added this however **whenever I build parity it seems to be picking up the wrong version.**

Here is the error
_Johns-MacBook-Pro:parity johnwhitton$ cargo build --release
   Compiling parity-polyapp v0.1.0 (https://github.com/johnwhitton/parity-polyapp.git#**e915574a**)
/Users/johnwhitton/.multirust/toolchains/stable/cargo/git/checkouts/parity-polyapp-56137d284b77d9f9/master/src/lib.rs:3:1: 3:28 error: can't find crate for `parity_webapp` [E0463]_

If you notice the git version it is looking at is **e915574a** but the latest version is **7d6d3aa3**
Can someone explain how to ensure it picks up the latest version.

Regards,

John

Files of Interest include (note in my forked parity I'm using[ johnwhitton_branch1](https://github.com/johnwhitton/parity/tree/johnwhitton_branch1))
parity [cargo.toml](https://github.com/johnwhitton/parity/blob/johnwhitton_branch1/webapp/Cargo.toml)
parity [apps.rs](https://github.com/johnwhitton/parity/blob/johnwhitton_branch1/webapp/src/apps.rs)
parity-polydapp [cargo.toml](https://github.com/johnwhitton/parity-polyapp/blob/master/Cargo.toml)

**Comment by tomusdrw** [comment]
There is already an entry for `parity-polyapp` in your `Cargo.lock`.
You should:
1. Bump version of your app in `webapp/Cargo.toml` (and also in `parity-polyapp/Cargo.toml`)
1. or checkout `Cargo.lock` which does not know about your `parity-polyapp`,
1. or  use local path in `webapp/Cargo.toml` (`parity-polyapp = { path = "../../parity-polyapp" }`)

**Comment by johnwhitton** [comment]
So in summary
1) I made a mistake when I first created my polydapp-> cargo.toml (in that I didn’t include
[dependencies]
parity-webapp = { git = "https://github.com/tomusdrw/parity-webapp.git" }
2) Then in Parity when I did a cargo build —release it failed to compile and left a corrupted cargo.lock
3) The only way to remove that was to git checkout 26ed38ecc293d9922be3fc28a8fb564b2d4051d6 — Cargo.lock
4) I fixed my polydapp-> cargo.toml
5) reran cargo build —release
And this resolved my issue
